services:
  - type: web
    name: course-recommender
    runtime: python
    buildCommand: |
      pip uninstall scikit-learn -y
      pip install scikit-learn==1.2.2
      pip install -r requirements.txt

    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app  # Critical for port binding
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000  # Must match app.py