services:
  - type: web
    name: course-recommender
    runtime: python
    buildCommand: |
      pip install --force-reinstall -r requirements.txt
      python -c "import os; print('Python version:', os.sys.version)"  # Verify Python
      python -c "import surprise; print('Surprise installed!')"
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app  # Critical for port binding
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000  # Must match app.py